### ISSUE TITLE
Need build instructions

### ISSUE THREAD

**Issue by marcrblevins** [Eliovp/amdmemorytweak#1]
Need build instructions

**Comment by Eliovp** [comment]
https://github.com/Eliovp/amdmemorytweak#building

:)

**Comment by khunpoum** [comment]
ubuntu 16.04

# git clone https://github.com/Eliovp/amdmemorytweak.git
# cd amdmemorytweak/
# g++ amdmemorytweak.cpp -lpci -lresolv

amdmemorytweak.cpp:36:63: fatal error: pci/pci.h: No such file or directory
compilation terminated.

**Comment by Eliovp** [comment]
libpci-dev  is what you need

Op zo 24 mrt. 2019 om 11:19 schreef khunpoum <notifications@github.com>:
