### ISSUE TITLE
Settings not applying?

### ISSUE THREAD

**Issue by integralfx** [Eliovp/amdmemorytweak#13]
![Image](https://cdn.discordapp.com/attachments/305981966292090881/567606955498143747/unknown.png)

As shown in the image above, my timings are not applying. I've tried 18.12.3 and 19.4.1 drivers, but they don't work either.

I also tried running GPU-Z render test while applying the timings, but that doesn't work.

I also idle at 2000MHz memory frequency so I think that might be causing it. My friend with an RX 580 also has the same issue I have and he also idled at 2000MHz.

Specs:
Nitro+ 570 4GB
Win 10 1809

**Comment by Eliovp** [comment]
You ran CMD prompt as admin?
CL has a bug, will be fixed in next release, although setting it for GDDR5 doesn't really do anything but negative effects :p

**Comment by integralfx** [comment]
Yeah, I ran command prompt as admin, as shown in the top left.

I can drop CL to 16 but I don't notice any performance improvements and stability seems to be the same.

**Comment by Eliovp** [comment]
For GDDR5, try to tweak things such as RFC/RC, .. when on a modified vbios, there isn't "that" much to tweak, most of the public available straps are too tight anyway.. touching something results mostly in a crash..

**Comment by integralfx** [comment]
![Timings](https://i.imgur.com/YiLNstM.jpg)

These are the timings I use on my Hynix AJR. I think tRFC is a bit too tight because I get 2 errors after 3 hours of gaming. I'll try upping it a bit and seeing if that fixes it.

**Comment by datspike** [comment]
Seems like RP_WRA is the most valuable timing at least for bandwidth (pocl\oclmembench)

**Comment by integralfx** [comment]
> For me it seems like on GDDR5 RP_WRA is the most valuable timing at least for bandwidth (pocl\oclmembench)

Yeah tRP_WRA helps a bit with bandwidth and so do tR2W, tRFC and WL.

**Comment by higi** [comment]
> 
> 
> ![Timings](https://camo.githubusercontent.com/fada631e723ce77917f9e64acc72e5dd22e4fb51/68747470733a2f2f692e696d6775722e636f6d2f59694c4e73744d2e6a7067)
> 
> These are the timings I use on my Hynix AJR. I think tRFC is a bit too tight because I get 2 errors after 3 hours of gaming. I'll try upping it a bit and seeing if that fixes it.

Hey where i can get this Timings Decoder. THX

**Comment by integralfx** [comment]
> Hey where i can get this Timings Decoder. THX

https://github.com/integralfx/BIOSTimingsDecoder

**Comment by Eliovp** [comment]
Closing this as the "issue" is resolved ;-)
