### ISSUE TITLE
Bsod on windows

### ISSUE THREAD

**Issue by crazyrigga** [Eliovp/amdmemorytweak#14]
Setup
5 vega 56(4 hynix) 1(samsung). Motherboard Asus b250 mining expert. Ram 8 gb. Processor g4600
After applying settings for memory timings using cmd as administrator and starting the miner (teamred miner 0.4.4). I get bsod saying "Video Scheduler Internal error ".
I have tried both 0.16 and 0.17 version no matter what settings for powerplay table that i use it always gives me bsod.
Please could you help me what am i doing wrong.

**Comment by Eliovp** [comment]
Are you getting a BSOD when trying to mine something else such as ETH with Claymore or Phoenix?

**Comment by crazyrigga** [comment]
Monero with teamred miner

**Comment by crazyrigga** [comment]
Ok i will check that and will let you know

**Comment by crazyrigga** [comment]
Checked on pheonixminer and getting the same bsod

**Comment by crazyrigga** [comment]
Either i apply on a single gpu or all of them the result is same following are the settings i am using

WinAMDTweak.exe --i 0,1,2,3,4 --RAS 22 --RCDRD 17 --RCDWR 4 --RC 35 --RP 13 --RRDS 4 --RRDL 4 --RFC 148 --REF 15600
WinAMDTweak.exe  --i 4 --RAS 22 --RCDRD 17 --RCDWR 4 --RC 35 --RP 13 --RRDS 4 --RRDL 4 --RFC 148 --REF 15600

**Comment by Eliovp** [comment]
RAS is way to low

try to do step by step, first change a single value, then the next, etc;..

**Comment by crazyrigga** [comment]
I have increased  RAS value to 28 and RCDWR to 12 and now the bsod error msg has changed to " thread stuck in device driver"

**Comment by crazyrigga** [comment]
stopped getting the BSOD with new driver 19.4.1. finally can tweak now. thank you for the wonderful tool
