### ISSUE TITLE
Feature request: --version CLI option

### ISSUE THREAD

**Issue by melt7777** [Eliovp/amdmemorytweak#15]
Hello elio, and thank you very much for your great work!

This is a feature request to add a command line option `--version` to output the program's version, example: "amdmemweak 0.x.x" 

This will be helpful in our changelogs and automations, and will ensure your application follows good coding convention as well. Thank you!!!

~ melt
getpimp.org | miner.farm

**Comment by Eliovp** [comment]
Fair point!

Will do in next one :)
