### ISSUE TITLE
Radeon VII - not yet implemented?

### ISSUE THREAD

**Issue by higi** [Eliovp/amdmemorytweak#16]
Hey,

Radeon VII :
C:\amdtweak>WinAMDTweak.exe --i 1 --current
GPU 1:  Radeon VII      Memory state: 0x11E (1200MHz)
Timing 1          CL: 22          RAS: 33         RCDRD: 14       RCDWR: 10
Timing 2          RCAb (RC): 47   RCPb (RC): 47   RPAb (RP): 14   RPPb (RP): 14
Timing 3          RRDS: 4         RRDL: 4         RTP: 5
Timing 4          FAW: 16
Timing 5          CWL: 7          WTRS: 4         WTRL: 9
Timing 6          WR: 16
Timing 7          RREFD: 8
Timing 8          RDRDDD: 3       RDRDSD: 2       RDRDSC: 1       RDRDSCL: 3
Timing 9          WRWRDD: 3       WRWRSD: 2       WRWRSC: 1       WRWRSCL: 3
Timing 10         WRRD: 1         RDWR: 21
Timing 12         REF: 3900
Timing 13         MRD: 8          MOD: 15
Timing 14         XS: 270
Timing 16         XSMRS: 8
Timing 17         PD: 8   CKSRE: 20       CKSRX: 20
Timing 20         RFCPB: 160      STAG: 4
Timing 21         XP: 8   CPDED: 2        CKE: 8
Timing 22         RDDATA: 20      WRLAT: 5        RDLAT: 18       WRDATA: 1
Timing 23         CKESTAG: 66
RFC Timing        RFC: 260

- gui BETA tool on Radeon VII showing as:
https://imgur.com/a/e5vAf03

RAS2RAS 255 etc is this ok? or not yet implemented? If not could u please implement it.

is it possible to pass parameters with GUI tool? Like i want to apply original values (only some) for Radeon VII. Cant get thees parameters working with non GUI version:(
WinAMDTweak.exe --i 1 --TRCDW 31 --TRCDWA 31 --TRCDR 31 --TRRD 15 --TR 127
WinAMDTweak.exe --i 1 --TR2W 31 --TW2R 31 --TCL 31
WinAMDTweak.exe --i 1 --TRP_RDA 127 --TRP 63 --TRFC 511
WinAMDTweak.exe --i 1 --TFAW 31 --TCRCRL 7 --TCRCWL 31 TFAW32 15
WinAMDTweak.exe --i 1 --ACTRD 27 --ACTWR 22 --RASMACTRD 44 --RASMACTWR 49

btw:
- old tool showing as current: RFC Timing  RFC: 260 and BETA GUI showing  tRFC 511
- ohgodadecode showing me differend values WinAMDTweak.exe --i 1 --current (should be showing same?)

for example:
 as C:\amdtweak>ohgodadecode.exe BBB000000000000022889D0073EE8D53805515133ECF560C004E26017E0514206A8900A00200312 01C143840C5303F17

When i get this working i will send my tweaking results. THX for this awesome tool

**Comment by Eliovp** [comment]
Ha, yeah, i just noticed the bug in the GUI version for R7, that's on me :)

Will be fixed in next release

**Comment by higi** [comment]
amazing ty:)

**Comment by Eliovp** [comment]
Try latest release ;-)

**Comment by higi** [comment]
Hello, tested new version, unfortunately when i run it (as administrator) it immediately open and close. (old version opens normaly)
It will also create file 1002-67DF.xmr.

<values cksre="2" cksrx="2" cke_pulse="10" cke="10" seq_idle="7" w2r="15" r2r="5" ccld="2" r2w="26" rc="60" rrd="5" rcdra="22" rcdr="24" rcdwa="13" rcdw="12" rfc="97" trp="22" rprda="24" rpwra="44" wdatatr="0" t32aw="0" crcwl="22" crcrl="3" faw="0" ras="38" rasmactwr="24" rasmactrd="21" actwr="10" actrd="13" ras2ras="54" rp="23" wrplusrp="30" busturn="12" timing="0" zerorpm="False" tdplimit="0" maxtemp="75">
  <mem>
    <p0 enabled="1" clock="300" vddc="750" />
    <p1 enabled="2" clock="1000" vddc="800" />
    <p2 enabled="4" clock="2050" vddc="950" />
    <p3 enabled="0" clock="0" vddc="0" />
  </mem>
  <core>
    <p0 enabled="1" clock="300" vddc="750" />
    <p1 enabled="2" clock="850" vddc="790" />
    <p2 enabled="4" clock="900" vddc="800" />
    <p3 enabled="8" clock="950" vddc="810" />
    <p4 enabled="64" clock="1000" vddc="820" />
    <p5 enabled="32" clock="1050" vddc="830" />
    <p6 enabled="64" clock="1100" vddc="840" />
    <p7 enabled="128" clock="1150" vddc="850" />
  </core>
  <fan>
    <p0 temp="30" percent="19" />
    <p1 temp="48" percent="81" />
    <p2 temp="63" percent="84" />
    <p3 temp="76" percent="91" />
    <p4 temp="85" percent="91" />
  </fan>
</values>

**Comment by Eliovp** [comment]
Hey Higi

Here's a newer version, however, i'll release a better version later on.

[Here](http://eliovp.com/x64GUIVersion.zip)

**Comment by higi** [comment]
thx for quick update, GUI is now showing:)
anyway changing RFC fromk 260 to 255 then i press apply. it tells me "cannot parse number"
