### ISSUE TITLE
 new version with gui

### ISSUE THREAD

**Issue by foxwarernd** [Eliovp/amdmemorytweak#18]
downloaded, unpacked and run exe under windows. and nothing, no sign that launched

what could be wrong?

**Comment by Eliovp** [comment]
I'm trying to reproduce. 
Installed a fresh system here, opened it up, installed .net framework and runs just fine.
Both x86 and x64 version.

I need a bit more info.
I will as well drop a new version with more error reporting.

The only thing i could immediately think of is administrator privileges.

**Comment by Eliovp** [comment]
Could you do me a favor and run this one (error reporting)

[Link](http://eliovp.com/AMDMemTweakErrorReporting.zip)

**Comment by foxwarernd** [comment]
![image](https://user-images.githubusercontent.com/19841581/56731180-8528a480-6762-11e9-9a13-9507661bc4d5.png)

**Comment by foxwarernd** [comment]
win 10 x64

**Comment by foxwarernd** [comment]
> I'm trying to reproduce.
> Installed a fresh system here, opened it up, installed .net framework and runs just fine.
> Both x86 and x64 version.
> 
> I need a bit more info.
> I will as well drop a new version with more error reporting.
> 
> The only thing i could immediately think of is administrator privileges.

with admin privileges the same

**Comment by Eliovp** [comment]
Thank you for your screenshot! 
Can you run this version and send over the log it generates.

[Link](http://eliovp.com/AMDMemoryTweakWithLog.zip)

Thank you!

**Comment by foxwarernd** [comment]
> Thank you for your screenshot!
> Can you run this version and send over the log it generates.
> 
> [Link](http://eliovp.com/AMDMemoryTweakWithLog.zip)
> 
> Thank you!

[amdtweak.log](https://github.com/Eliovp/amdmemorytweak/files/3116771/amdtweak.log)


cards installed 5 pcs.

**Comment by Eliovp** [comment]
Perfect!

**Comment by Eliovp** [comment]
Owkay, here we go. Try this

[Link](http://eliovp.com/AMDMemoryTweakbeta3.zip)

**Comment by foxwarernd** [comment]
![image](https://user-images.githubusercontent.com/19841581/56744222-c16afd80-6780-11e9-9b90-87bfd001140e.png)

[amdtweak.log](https://github.com/Eliovp/amdmemorytweak/files/3117418/amdtweak.log)

**Comment by Eliovp** [comment]
ok

Still very much beta but this will solve your problem.

[Link](http://eliovp.com/x64GUIVersion.zip)

**Comment by foxwarernd** [comment]
excellent! now it starts!

**Comment by Eliovp** [comment]
Good!

**Comment by gammaburster1** [comment]
Same issue here Eliovp.
6 x vega64's
driver: 18.6.1
OverdriveNtool

![Screenshot (3)](https://user-images.githubusercontent.com/50055457/56853473-94405b80-68f6-11e9-82cd-2b1070a4d11d.png)

**Comment by gammaburster1** [comment]
Disregard my message above. I installed driver version 19.4.1 and it is all good.
Thank you for this tool. It kicks ass!
