### ISSUE TITLE
Question in regards to correct values

### ISSUE THREAD

**Issue by eketubol** [Eliovp/amdmemorytweak#2]
Hi, I have successfully built the tool but I have zero knowledge on what values should be inputted into the tool. I believe it might be very good to have a brief description on what each option does and what is necessary to increase hashrate on specific devices, for example i run RX 570's and would love to get these hashing higher I just do not know what values to change in order to do so.

**Comment by Eliovp** [comment]
The only suggestion i can give you here is to do some research mate.
You can find numerous of articles explaining what specific timing values do.
The best way to learn is to try ;-)
