### ISSUE TITLE
Opening Problem

### ISSUE THREAD

**Issue by mohsenack** [Eliovp/amdmemorytweak#21]
Hi Eliovp, I tried to use the latest version, but it shows this error, anything to do? 12 Vega 64 - 19.4.1 on Windows 10
![1](https://user-images.githubusercontent.com/50381582/57329856-d3a64d80-7129-11e9-99a7-8e40115c792b.jpg)

**Comment by Eliovp** [comment]
mmm, looks like it didn't detect any devices. Weird

Can you give me some more info.

Are you running srbminer or did you run it at an earlier stage?
I don't think it has anything to do with it  but still.. 

Do you mind trying to upgrade to 19.4.3 ?
If you still experience problems, let me know here, i'll build you a release that generates a log file upon trying to open the tool.

In any other case, you can always still use the CLI version. 

Cheers

**Comment by mohsenack** [comment]
Yes, I was using srbminer before. well I had problem with upgrading to 19.4.3, it was freezing on "detecting devices" screen, so i just went for 19.4.1.

**Comment by mohsenack** [comment]
Also as an update, I tried to open CLI version, but before it shows anything, it disappears.

**Comment by Eliovp** [comment]
While you were trying to update drivers, the installer froze upon detecting devices?
You using risers or something?

Anyhow, CLI version, don't just double click on it.
open a CMD prompt (as admin)
navigate to the folder where the cli version is
cd c:/.....
and execute the cli version.

Or create a batch file and end the batch file with a pause.

**Comment by Eliovp** [comment]
No reply, guess all is good? Closing
