### ISSUE TITLE
BAT File and Autostart needed asap for Windows 

### ISSUE THREAD

**Issue by postalman** [Eliovp/amdmemorytweak#23]
Need some support and example how to create .bat file for autostart timings and powerplay table.

**Comment by Eliovp** [comment]
I'm going to refer you to BitsBeTrippin his video's for this.

[Video 1](https://www.youtube.com/watch?v=PrkNpl2Y3h4)
[Video 2](https://www.youtube.com/watch?v=BJMZhbfoYA8)

Cheers
