### ISSUE TITLE
Option to set clocks and voltages and disable Pstates in command line version

### ISSUE THREAD

**Issue by evlo** [Eliovp/amdmemorytweak#25]
Hi,

gui version has option to disable power states, set voltages and frequency for memory and gpu, that is great, however these options are missing from CLI.

It would be nice to have it there as on windows we could then use just one tool to set everything - no need for overdriveN tool. It would simplify things. And I think since gui supports it alrady it is most likely almost done.

**Comment by Eliovp** [comment]
You can add these things to the CLI version if you want
https://github.com/GPUOpen-LibrariesAndSDKs/display-library

GUI version was built to make things easier for beginners.
