### ISSUE TITLE
feature request - apply straps

### ISSUE THREAD

**Issue by evlo** [Eliovp/amdmemorytweak#26]
Hi,

I think lot of people would love to have option to apply strap directly, just pass it to the app, let app decode timings from it and apply.

Will you have time to do it? :)

**Comment by Eliovp** [comment]
It's not really on my todo list tbh .. 
There's third party tools to do that.
Cheers

**Comment by evlo** [comment]
Fair enough, can you share a link to such a tool? :)

**Comment by Eliovp** [comment]
Uhm, first hit in google: https://www.overclock.net/forum/67-amd/1629357-r_timings-encode-decode-rx-r9-memory-straps.html

Cheers!
