### ISSUE TITLE
tCL change does nothing

### ISSUE THREAD

**Issue by thepusher90** [Eliovp/amdmemorytweak#27]
I tweaked my Red Devil Vega 56 and I noticed that changing the tCL does nothing at all for me. I put it all the way down to 1 and applied and nothing happened, so I assume the steps in between did nothing at all, because it had not impact on the performance too. Some stats improved the performance greatly, but I don't know if there were other timings that were not impacted by changing them. I just noticed it, because everyone on reddit said that tCL should have the biggest impact on performance.

I have to add that I flashed my Red Devil 56 with a reference Powercolor Vega 64 Bios. I don't know if this has any impact on it.

I tested it with the memory benchmark, aswell as three games.

I am using it on Win 10 GUI version and drivers 19.4.3 aswell as 19.5.1 were tested by me.

**Comment by Eliovp** [comment]
There's a min/max for tCL, anything under/above will just default back to stock.
Raise it by 2 or something, same for tRAS, it increases stability.

Cheers
