### ISSUE TITLE
Feature request - timings decoder

### ISSUE THREAD

**Issue by higi** [Eliovp/amdmemorytweak#28]
Hey,

is it possible to add something like this?
https://github.com/integralfx/BIOSTimingsDecoder

i mean just input field to put allready created memory straps. So i can save it as Export in your Amazing APP:)

i know similar feature was requested before, but other tools cant generate your exports:( u allready implemented overdrive, so it would be really nice to have it all in one tool:) Maybe build in atiflash too:D

**Comment by Eliovp** [comment]
XL Version supports decoding & encoding
Cheers
