### ISSUE TITLE
feature request - use Mesa driver

### ISSUE THREAD

**Issue by mmeyran** [Eliovp/amdmemorytweak#29]
Hello,
Considering the Linux driver's kernel-side element is common to both the closed source and the open source driver, is it possible to make your tool work with the open source driver too? If not, why?
Regards

**Comment by Eliovp** [comment]
I don't really see the point here.. 
The open source mesa driver, for as far as i know, has no performance applications.. 

Anyhow, the source here is open, no one's stopping you from trying ;-)

Cheers
