### ISSUE TITLE
Modify your build command?

### ISSUE THREAD

**Issue by marcrblevins** [Eliovp/amdmemorytweak#3]
Can you please change your build command from:
g++ amdmemorytweak.cpp -lpci -lresolv

To:
g++ amdmemorytweak.cpp -lpci -lresolv -o amdmemorytweak

Otherwise it produces executalbe a.out

Cheers,
Marc

**Comment by Eliovp** [comment]
Fair point! Bad assumption to think that most people would automatically do this :)

Thank you for your suggestion!
