### ISSUE TITLE
Could you release GUI source code ?p

### ISSUE THREAD

**Issue by Flygamer007** [Eliovp/amdmemorytweak#33]

**Comment by Eliovp** [comment]
Don't really see a reason why?
It's exactly the same as the open source CLI version except the ADL part (Setting clocks and such...)

**Comment by Flygamer007** [comment]
As I know timing is a string as "999000000000000022559D0031627C4990551313BC0D060C004C04017D0714204A8900A00200712419123138C02D3D17"
So I want to see this string how to change when I modify by WinAMDTweak tool?

**Comment by Llorx** [comment]
I want to modify it and do a PR which will load and apply XML profiles automatically.

**Comment by Llorx** [comment]
Also, open source is important if you want users to trust your software :-/
