### ISSUE TITLE
Can't start 

### ISSUE THREAD

**Issue by ayman-alawneh** [Eliovp/amdmemorytweak#34]
![Capture](https://user-images.githubusercontent.com/37948390/58439229-3b4c1a80-8090-11e9-9187-f2debc0752d1.JPG)
Keep getting this error 
tried several drivers uninstalled msi after burner 
ran as admin

**Comment by Eliovp** [comment]
Did you include the driver?
IOMap & IOMap64 ?

**Comment by ayman-alawneh** [comment]
for vega 64
I tried 19.4.1
19.5.2
19.3.1

**Comment by Eliovp** [comment]
You didn't answer my question ;-)

Did you download the driver and included it into the same directory as AMD Memory Tweak.exe?

"IOMap"

**Comment by ayman-alawneh** [comment]
oh yeah it was already downloaded in the folder

**Comment by bryanjs** [comment]
I have this same problem. I have IOMap.sys and IOMap64.sys in the same direction as well.

**Comment by Transporter33** [comment]
Not had this issue for ages then its started again, any fixes?

**Comment by SiegHeil** [comment]
you can use old version (0.1.8.1)
