### ISSUE TITLE
Elio, i don't know how to put DeviceID=6811 for R9 370 4 Gb card

### ISSUE THREAD

**Issue by ilyag2** [Eliovp/amdmemorytweak#36]
Elio, i don't know how to put DeviceID=6811 for R9 370 4 Gb card and therefore to compile the program for the pitcairn.

**Comment by SiegHeil** [comment]
if they have HBA memory, then you can try adding code by analogy as in LookupDeviceName, IsRelevantDeviceID, IsR9, DetermineMemoryType (from windows cli sources)

**Comment by ilyag2** [comment]
Thanks for reply, but I have gddr 5, and I don’t understand what to do in my case of r9 370 4gb04.06.2019, 00:09, "SiegHeil" <notifications@github.com>:if they have HBA memory, then you can try adding code by analogy as in LookupDeviceName, IsRelevantDeviceID, IsR9, DetermineMemoryType (from windows cli sources)

**Comment by Eliovp** [comment]
You just have to add the Device ID to the supported ID list. Recompile and done.
