### ISSUE TITLE
Thanks for reply, but I have gddr 5, and I don’t understand what to do in my case of r9 370 4gb

### ISSUE THREAD

**Issue by ilyag2** [Eliovp/amdmemorytweak#38]
Thanks for reply, but I have gddr 5, and I don’t understand what to do in my case of r9 370 4gb04.06.2019, 00:09, "SiegHeil" <notifications@github.com>:if they have HBA memory, then you can try adding code by analogy as in LookupDeviceName, IsRelevantDeviceID, IsR9, DetermineMemoryType (from windows cli sources)

**Comment by Eliovp** [comment]
Should work just fine on a 370, i don't see a reason why not.

please give some more info
