### ISSUE TITLE
Running from cmd ?

### ISSUE THREAD

**Issue by nemye** [Eliovp/amdmemorytweak#39]
Im not getting any output when I run from cmd, and if I try as admin, I get "Failed to load EIO.dll"

GUI works fine, but I am trying to create shortcut to apply my stable settings when I power up my PC.

I built as x64 in debug, should I be doing that another way?

**Comment by Bathmat** [comment]
I am getting the same error on Win10 1903 using 18.6.1 drivers. GUI version 0.2.3 works fine. 

```
amdmemtweak>WinAMDTweak.exe --version
AMD Memory Tweak Windows CLI version 0.1.9
```

**Comment by Bathmat** [comment]
Looks like it just wasn't included with the latest release. I found it in a previous release: https://github.com/Eliovp/amdmemorytweak/releases/tag/0.1.8.1

Downloaded from there and appears to be working now.

**Comment by nemye** [comment]
I have the file which is the weird part. I am on the latest drivers, which I suppose is a likely candidate causing the issue.

**Comment by Eliovp** [comment]
Closing this because the answer has been given by bathmat

**Comment by nemye** [comment]
His answer did not resolve anything as I stated I already had the file. This was never resolved
