### ISSUE TITLE
WTRL value change does nothing

### ISSUE THREAD

**Issue by WINDY-WINDWARD** [Eliovp/amdmemorytweak#4]
i tried increasing and reducing the value it had no effect 
my rig:
vega 64 x3

**Comment by Eliovp** [comment]
Some values won't have a direct "noticable" effect. 
That however doesn't mean they are there for no reason.
I just verified to be sure that i didn't miss anything. It's working as it suppose to.

**Comment by WINDY-WINDWARD** [comment]
ok cool thanks
