### ISSUE TITLE
GPU distinguishing 

### ISSUE THREAD

**Issue by karloballa** [Eliovp/amdmemorytweak#40]
Is there a way to distinguish same GPUs? For example, identify GPU  by Bus or something else that can be accessed from OpenCL?

Thanks!

**Comment by Eliovp** [comment]
Yes, that is possible.
It all depends on how the enumeration is done. Which is different in many cases. 

Most common rule can mostly be used here where GPU 0 (the first one) is the first 16x slot closest seated to the CPU.
