### ISSUE TITLE
CoreControl and MemoryControl Command line options missing?

### ISSUE THREAD

**Issue by frontstltd** [Eliovp/amdmemorytweak#41]
Cant find CoreControl and MemoryControl Command line options for windows batch file,tried almost every option eg. GPU_P0=853;801;0

**Comment by Eliovp** [comment]
Mm, might be a bit confusing, i get that.

The command line versions do not have clock control.
They're purely written for MMIO Register control. Nothing else.

The UI version has clock control, it however does not support command line options.

Cheers
