### ISSUE TITLE
Ubuntu 18.04.4, driver amdgpu-pro-20.20-1089974 no effect

### ISSUE THREAD

**Issue by PNixx** [Eliovp/amdmemorytweak#46]
My Vega56 timing apply no effect with a new drivers 20.20-1089974, ethereum 33.9mh/s.
With old 19.20-812932 driver - 45mh/s.

**Comment by Eliovp** [comment]
Well, i would suggest to use 19.20 then :)

I just did a quick test on 20.20 , kernel 5.8.0, Vega 56, stock clocks, REF changed to 9k
20.10 -> 36.62 Mh
20.20 -> 35.97 Mh

Changed REF to 22k
20.20 -> 36.71 Mh

Works fine..

**Comment by PNixx** [comment]
19.20 not working with rx 5700 xt. I use a single system different card.

**Comment by PNixx** [comment]
@Eliovp I see applying timings for incorrect memory state:
```
$ sudo amdmemorytweak/amdmemtweak --i 5 --c
GPU 5:  Vega 10 XT [Radeon RX Vega 64]	pci:0000:0b:00.0
Memory state: 800MHz
Memory: Hynix HBM2
```
Current working memory 949Mhz.

**Comment by perestoronin** [comment]
> My Vega56 timing apply no effect with a new drivers 20.20-1089974, ethereum 33.9mh/s.
> With old 19.20-812932 driver - 45mh/s.

I have same issue on Vega56 :(
